"""2 migration

Revision ID: 1fbee0e1a481
Revises: dac08bfc52fb
Create Date: 2024-05-22 15:55:07.363144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fbee0e1a481'
down_revision: Union[str, None] = 'dac08bfc52fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    kind_enum = postgresql.ENUM('film', 'cartoon', 'serial', name='kind', create_type=True)
    kind_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('film', sa.Column('kind', postgresql.ENUM('film', 'cartoon', 'serial', name='kind', create_type=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('film', 'kind')
    # ### end Alembic commands ###
